#
###################################
# Site wide configuration
####################################
#
title: Shibbir Ahmed | Web developer
url: # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title
paginate:          4

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Shibbir Ahmed
  github: shibbir
  twitter: shibbir_io
  about: shibbir
  disqus-shortname: shibbir
